INSERT INTO products (name, price, created_at, updated_at) VALUES
('Smartphone X1', 599, NOW(), NOW()),
('Laptop Pro', 1299, NOW(), NOW()),
('Wireless Earbuds', 129, NOW(), NOW()),
('4K Smart TV', 799, NOW(), NOW()),
('Gaming Console', 499, NOW(), NOW()),
('Fitness Tracker', 79, NOW(), NOW()),
('Tablet Air', 349, NOW(), NOW()),
('Bluetooth Speaker', 89, NOW(), NOW()),
('Smartwatch Elite', 199, NOW(), NOW()),
('Drone Explorer', 399, NOW(), NOW()),
('VR Headset', 299, NOW(), NOW()),
('Portable SSD', 129, NOW(), NOW()),
('Wireless Mouse', 39, NOW(), NOW()),
('Mechanical Keyboard', 109, NOW(), NOW()),
('Noise-Canceling Headphones', 249, NOW(), NOW()),
('Smart Home Hub', 129, NOW(), NOW()),
('Portable Charger', 49, NOW(), NOW()),
('Wi-Fi Router', 89, NOW(), NOW()),
('Digital Camera', 449, NOW(), NOW()),
('E-book Reader', 119, NOW(), NOW()),
('Gaming Mouse', 69, NOW(), NOW()),
('Curved Monitor', 349, NOW(), NOW()),
('Smart Thermostat', 179, NOW(), NOW()),
('Wireless Printer', 159, NOW(), NOW()),
('Action Camera', 229, NOW(), NOW()),
('Smart Lock', 149, NOW(), NOW()),
('Portable Projector', 299, NOW(), NOW()),
('Wireless Charging Pad', 39, NOW(), NOW()),
('Smart Scale', 59, NOW(), NOW()),
('Mesh Wi-Fi System', 199, NOW(), NOW()),
('Graphic Tablet', 179, NOW(), NOW()),
('Smart Light Bulbs', 29, NOW(), NOW()),
('Portable Monitor', 169, NOW(), NOW()),
('USB-C Hub', 49, NOW(), NOW()),
('Smart Doorbell', 129, NOW(), NOW()),
('External GPU', 299, NOW(), NOW()),
('Wireless Keyboard', 59, NOW(), NOW()),
('Smart Plug', 25, NOW(), NOW()),
('Dash Cam', 89, NOW(), NOW()),
('Portable Scanner', 99, NOW(), NOW()),
('Smart Smoke Detector', 79, NOW(), NOW()),
('Wireless Webcam', 69, NOW(), NOW()),
('NAS Storage', 299, NOW(), NOW()),
('Smart Air Purifier', 159, NOW(), NOW()),
('Gaming Headset', 89, NOW(), NOW()),
('Portable Bluetooth Printer', 79, NOW(), NOW()),
('Smart Water Bottle', 39, NOW(), NOW()),
('360-Degree Camera', 199, NOW(), NOW()),
('Ergonomic Vertical Mouse', 49, NOW(), NOW()),
('Smart Coffee Maker', 129, NOW(), NOW());
